name: Repository secret CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print repo secret
        run: echo "API KEY is $API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Simulate build
        run: echo "Building project..."

      - name: Simulate tests
        run: echo "Running tests..."